version: '3'

services:
    web:
        image: nginx:1.12.2
        ports:
            - "${EXTERNAL_PORT:-80}:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www:ro
    php:
        build: docker/php
        volumes:
            - ./app:/var/www/app
            - ./bin:/var/www/bin
            - ./composer.json:/var/www/composer.json
            - ./composer.lock:/var/www/composer.lock
            - ./package.json:/var/www/package.json
            - ./package-lock.json:/var/www/package-lock.json
            - ./node_modules:/var/www/node_modules
            - ./src:/var/www/src
            - ./tests:/var/www/tests
            - ./vendor:/var/www/vendor
            - ./web:/var/www/web
            - .:/var/www/
        env_file:
            - php-variables.env
        links:
         - db:db
    db:
        image: mongo:latest
        volumes:
          - ./data/mongodb:/data/db
        ports:
            - 27017:27017
    composer:
        image: composer
        volumes:
            - .:/app
        env_file:
            - php-variables.env
    mailcatcher:
        image: tophfr/mailcatcher:latest
        ports:
            - "${EXTERNAL_MAILCATCHER_PORT:-81}:80"
        expose:
            - "25"
